#!/usr/bin/env bash
# displays Best School and then Hi on a new line.

COUNTER=0
while [ $COUNTER -lt 11 ]
do

  if [ $COUNTER = 9 ]
  then
      echo "Hi"
  else
     echo "Best School"
  fi
    let COUNTER+=1
done